import { Inter, Bebas_Neue } from "next/font/google";
import "./globals.css";

// inter and bebasNene font area here 
const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
});
const bebasNene = Bebas_Neue({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bebas",
});

// meta title and description area here 
export const metadata = {
  title: "Ridoy Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter.variable} ${bebasNene.variable}`}>
        {children}
      </body>
    </html>
  );
}
